Fix feature specs which test togglable features
Fixes:
```
undefined local variable or method `app' for #<Middleman::Application:0x52385740> (NameError)
      ./lib/middleman-core/step_definitions/server_steps.rb:57:in `block (4 levels) in <top (required)>'
      ./lib/middleman-core/step_definitions/server_steps.rb:56:in `each'
      ./lib/middleman-core/step_definitions/server_steps.rb:56:in `block (3 levels) in <top (required)>'
```

`Middleman::Application##after_configuration_eval` executes in the
`Application` instance context. Thus calling
`app.config_context.instance_exec(&p)` will error as `app` is implied in
the block but not defined as `app`.

Signed-off-by: Tom Dunlap <tdunlap@pivotal.io>